### ISSUE TITLE
Flood run controller log with corrupt PipelineRun resource

### ISSUE THREAD

**Issue by alxsap** [SAP/stewardci-core#20]
This simple pipelinerun resource results in endless log entries in the run controller log every second. The resource itself is never updated with an error message.

```yaml
apiVersion: steward.sap.com/v1alpha1
kind: PipelineRun
metadata:
  generateName: ok-
spec:
  args:
    a: b
    c: 5
  jenkinsFile:
    repoUrl: https://github.com/SAP-samples/stewardci-example-pipelines
    revision: master
    relativePath: success/Jenkinsfile
```

The reason for the error is the number `5`. `args` is a `map[string]string`.

Run Controller Log:
> E1119 14:01:54.795518       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.PipelineRun.Spec: v1alpha1.PipelineSpec.JenkinsFile: v1alpha1.JenkinsFile.Args: ReadString: expects " or n, but found 5, error found in #10 byte of ...|:"b","c":5},"jenkins|..., bigger context ...|-adf4-4201ac10000c"},"spec":{"args":{"a":"b","c":5},"jenkinsFile":{"relativePath":"success/Jenkinsfi|...
> E1119 14:01:54.799101       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.PipelineRun.Spec: v1alpha1.PipelineSpec.JenkinsFile: v1alpha1.JenkinsFile.Args: ReadString: expects " or n, but found 5, error found in #10 byte of ...|:"b","c":5},"jenkins|..., bigger context ...|-adf4-4201ac10000c"},"spec":{"args":{"a":"b","c":5},"jenkinsFile":{"relativePath":"success/Jenkinsfi|...
> E1119 14:01:55.802535       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190817222206-ee6c071a42cf/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: v1alpha1.PipelineRunList.Items: []v1alpha1.PipelineRun: v1alpha1.PipelineRun.Spec: v1alpha1.PipelineSpec.JenkinsFile: v1alpha1.JenkinsFile.Args: ReadString: expects " or n, but found 5, error found in #10 byte of ...|:"b","c":5},"jenkins|..., bigger context ...|-adf4-4201ac10000c"},"spec":{"args":{"a":"b","c":5},"jenkinsFile":{"relativePath":"success/Jenkinsfi|...
> E1119 14:01:56.805568       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190817222206-ee6c071a42cf/tools/cache/reflector.go:93: Failed to list *v1alpha1.PipelineRun: v1alpha1.PipelineRunList.Items: []v1alpha1.PipelineRun: v1alpha1.PipelineRun.Spec: v1alpha1.PipelineSpec.JenkinsFile: 
> […] continues with the last log line
