### ISSUE TITLE
pipelineRun processed multiple times with same state

### ISSUE THREAD

**Issue by alxsap** [SAP/stewardci-core#50]
Observed in load tests:
```yaml
  stateHistory:
  - finishedAt: "2019-12-16T12:05:45Z"
    startedAt: "2019-12-16T12:05:45Z"
    state: new
  - finishedAt: "2019-12-16T12:05:45Z"
    startedAt: "2019-12-16T12:05:45Z"
    state: preparing
  - finishedAt: "2019-12-16T12:05:45Z"
    startedAt: "2019-12-16T12:05:45Z"
    state: preparing
  - finishedAt: "2019-12-16T12:05:45Z"
    startedAt: "2019-12-16T12:05:45Z"
    state: cleaning
  - finishedAt: "2019-12-16T12:05:46Z"
    startedAt: "2019-12-16T12:05:45Z"
    state: cleaning
...
```
